### PR TITLE
Install dependabot

### PR DESCRIPTION
**Pull request by syucream**
looks useful to keep updating dependencies
https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates

### CODE REVIEW

**Comment by naoty** [comment]
@syucream Unlike Dependabot, GitHub's native Dependabot doesn't have the auto-merge feature. Are you sure that we will merge updating PRs manually every week?

**Comment by syucream** [comment]
@naoty hmm, the frequency is a bit high so how about `schedule.interval=monthly` with `open-pull-requests-limit=1` ?

**Comment by naoty** [comment]
@syucream It's OK with me.

**Comment by syucream** [comment]
@naoty Fixed! can you check it?

**Pull request merged**
